import { NavLink, Route, Routes } from 'react-router-dom';
import { Activity, BellRing, BookOpenText, CloudSun, Gauge, Menu, RadioTower, RefreshCw, Siren, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Dashboard, Watch, Stations, Advisories, Alerts, System } from './pages';
import { climateStream } from './api';

const nav = [{to:'/',label:'Overview',icon:Activity},{to:'/watch',label:'Heatwave watch',icon:Gauge},{to:'/stations',label:'Live stations',icon:RadioTower},{to:'/alerts',label:'Alerts',icon:Siren},{to:'/advisories',label:'Advisories',icon:BookOpenText},{to:'/system',label:'System',icon:RefreshCw}];
export default function App(){
  const [open,setOpen]=useState(false); const [connected,setConnected]=useState(false); const [updated,setUpdated]=useState(new Date()); const [revision,setRevision]=useState(0);
  useEffect(()=>{const stream=climateStream(()=>{setUpdated(new Date());setRevision(value=>value+1)});stream.onopen=()=>setConnected(true);stream.onerror=()=>setConnected(false);return()=>stream.close()},[]);
  return <div className="app-shell min-h-screen lg:flex">
    <header className="mobile-header flex items-center justify-between p-4 text-white lg:hidden"><Brand/><button className="icon-button" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
    {open?<button className="fixed inset-0 z-10 bg-slate-950/35 backdrop-blur-sm lg:hidden" aria-label="Close menu" onClick={()=>setOpen(false)}/>:null}
    <aside className={`${open?'translate-x-0':'-translate-x-full'} sidebar fixed inset-y-0 left-0 z-20 flex w-64 flex-col px-5 py-7 text-white transition-transform lg:sticky lg:h-screen lg:translate-x-0`}><Brand/><p className="mt-2 text-xs text-teal-100/55">India climate operations</p><nav className="mt-10 space-y-1">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`nav-link flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold ${active(isActive)}`}><Icon size={18}/><span>{label}</span>{label==='Alerts'?<span className="ml-auto h-2 w-2 rounded-full bg-orange-400"/>:null}</NavLink>)}</nav><div className="sidebar-foot mt-auto pt-8"><p className="text-sm font-semibold text-white">Safer communities.<br/>A cooler tomorrow.</p><p className="mt-3 text-xs leading-5 text-teal-100/45">Data, insight and timely action for a more resilient India.</p></div></aside>
    <main className="min-w-0 flex-1 px-4 py-5 md:px-7 lg:px-9"><div className="mx-auto max-w-[1520px]"><div className="mb-5 flex items-center justify-end gap-5 border-b border-slate-200/80 pb-4 text-xs text-slate-500"><span className="flex items-center gap-2 font-semibold text-emerald-700"><i className={`h-2 w-2 rounded-full ${connected?'bg-emerald-500 animate-pulse':'bg-slate-300'}`}/>{connected?'Live stream connected':'Reconnecting'}</span><span className="hidden sm:inline">Last updated {updated.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span><button className="refresh-button" onClick={()=>{setUpdated(new Date());setRevision(value=>value+1)}}><RefreshCw size={14}/> Refresh</button></div><Routes><Route path="/" element={<Dashboard revision={revision}/>}/><Route path="/watch" element={<Watch revision={revision}/>}/><Route path="/stations" element={<Stations revision={revision}/>}/><Route path="/alerts" element={<Alerts revision={revision}/>}/><Route path="/advisories" element={<Advisories/>}/><Route path="/system" element={<System/>}/></Routes></div></main>
  </div>
}
const activeClass='bg-white/10 text-white shadow-inner ring-1 ring-white/10'; const inactiveClass='text-teal-50/60 hover:bg-white/5 hover:text-white';
function active(active:boolean){return active?activeClass:inactiveClass}
function Brand(){return <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-teal-400/15 text-teal-300"><CloudSun/></span><div><p className="font-bold leading-tight">Heatwave Intelligence</p><p className="text-[10px] font-semibold tracking-[.17em] text-teal-300">OPERATIONS</p></div></div>}
