import { NavLink, Route, Routes } from 'react-router-dom';
import { Activity, BellRing, CloudSun, Info, Menu, RadioTower, Sparkles, X, Circle } from 'lucide-react';
import { useState } from 'react';
import { Dashboard, Watch, Stations, Advisories, About } from './pages';

const nav = [{to:'/',label:'Dashboard',icon:Activity},{to:'/watch',label:'Heatwave Watch',icon:BellRing},{to:'/stations',label:'AWS Stations',icon:RadioTower},{to:'/advisories',label:'Advisories',icon:Sparkles},{to:'/about',label:'About',icon:Info}];
export default function App(){ const [open,setOpen]=useState(false); return <div className="app-shell min-h-screen lg:flex">
  <header className="mobile-header flex items-center justify-between p-4 text-white lg:hidden"><Brand/><button className="icon-button" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
  {open&&<button className="fixed inset-0 z-10 bg-slate-950/35 backdrop-blur-sm lg:hidden" aria-label="Close menu" onClick={()=>setOpen(false)}/>}<aside className={`${open?'translate-x-0':'-translate-x-full'} sidebar fixed inset-y-0 left-0 z-20 w-72 px-5 py-7 text-white transition-transform lg:sticky lg:block lg:h-screen lg:translate-x-0`}><Brand/><p className="mt-3 text-xs leading-5 text-teal-100/55">National climate operations console</p><p className="mt-10 px-3 text-[10px] font-bold uppercase tracking-[.2em] text-teal-100/35">Workspace</p><nav className="mt-3 space-y-1.5">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${isActive?'bg-white/10 text-white shadow-inner ring-1 ring-white/10':'text-teal-50/60 hover:bg-white/5 hover:text-white'}`}><Icon size={18}/><span>{label}</span><Circle className="ml-auto fill-current opacity-0 group-[.active]:opacity-100" size={6}/></NavLink>)}</nav><div className="status-card absolute bottom-7 left-5 right-5 rounded-2xl border border-white/10 p-4 text-xs text-teal-50/65"><div className="mb-2 flex items-center gap-2 font-semibold text-white"><span className="block h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]"/>All systems operational</div><p>14 stations · Updated just now</p></div></aside>
  <main className="min-w-0 flex-1 px-4 py-6 md:px-8 md:py-9 lg:px-12 lg:py-10"><div className="mx-auto max-w-[1480px]"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/watch" element={<Watch/>}/><Route path="/stations" element={<Stations/>}/><Route path="/advisories" element={<Advisories/>}/><Route path="/about" element={<About/>}/></Routes></div></main>
 </div> }
function Brand(){return <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-400/15 text-teal-300"><CloudSun/></span><div><p className="font-bold leading-tight">Heatwave</p><p className="text-xs font-semibold tracking-widest text-teal-300">INTELLIGENCE</p></div></div>}
