import { useCallback, useEffect, useMemo, useState } from 'react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowRight, Check, Database, Droplets, Gauge, RadioTower, Server, ShieldCheck, Sparkles, ThermometerSun, Wind } from 'lucide-react';
import { api } from './api';
import { Badge, EmptyState, ErrorBox, Loading, PageHead, severityColors } from './components';
import { regions, type Alert, type Forecast, type Observation, type Region, type Severity, type Snapshot, type Station, type Summary } from './types';

function useLoad<T>(path:string,revision=0){const[data,setData]=useState<T>();const[error,setError]=useState('');const load=useCallback(()=>{setError('');api<T>(path).then(setData).catch(e=>setError(e.message))},[path]);useEffect(()=>{let active=true;setError('');api<T>(path).then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[path,revision]);return{data,error,reload:load,setData}}
const time=(value:string)=>new Date(value).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});

export function Dashboard({revision=0}:{revision?:number}){
  const [region,setRegion]=useState<Region>('Northwest India'); const {data:snapshot,error}=useLoad<Snapshot>('/api/operations/snapshot',revision); const {data:forecast}=useLoad<Forecast[]>(`/api/forecast/${encodeURIComponent(region)}?days=7`,revision);
  const selected=snapshot?.regions.find(item=>item.region===region);
  return <><PageHead title="Operational overview" copy="Real-time heat conditions across India. Monitor extremes, validate signals and act with confidence." action={<select className="select min-w-52" value={region} onChange={event=>setRegion(event.target.value as Region)}>{regions.map(value=><option key={value}>{value}</option>)}</select>}/>{error?<ErrorBox message={error}/>:!snapshot?<Loading/>:<>
    <section className="situation-band"><div className="situation-icon"><AlertTriangle/></div><div className="min-w-0 flex-1"><p className="section-label">Current situation — India</p><h2>{snapshot.activeAlerts>2?'Elevated heat risk across multiple regions':'Heat conditions remain under active watch'}</h2><p>{snapshot.hottest.region} is currently hottest at {snapshot.hottest.latestTemp.toFixed(1)}°C. Teams should verify local conditions before public dissemination.</p><a href="/watch">View detailed analysis <ArrowRight size={15}/></a></div><div className="affected"><span>Regions under watch</span><strong>{snapshot.activeAlerts} / 7</strong><small>Live operational alerts</small></div></section>
    <div className="metrics-grid"><Metric icon={<ThermometerSun/>} label="Hottest region" value={`${snapshot.hottest.latestTemp.toFixed(1)}°C`} note={snapshot.hottest.region}/><Metric icon={<AlertTriangle/>} label="Active alerts" value={String(snapshot.activeAlerts)} note="Awaiting review or action" tone="danger"/><Metric icon={<RadioTower/>} label="Reporting stations" value={`${snapshot.reportingStations} / ${snapshot.totalStations}`} note={`${snapshot.dataQuality}% passing quality checks`} tone="good"/></div>
    <div className="dashboard-grid"><section className="panel chart-panel"><PanelTitle title="7-day temperature outlook" copy={`${region} · daily maximum with reference threshold`}/><div className="h-[330px]"><ResponsiveContainer><LineChart data={forecast}><CartesianGrid vertical={false} stroke="#e7edef"/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString('en-IN',{weekday:'short',day:'numeric'})} fontSize={11} tickLine={false} axisLine={false}/><YAxis domain={['dataMin - 3','dataMax + 3']} unit="°" fontSize={11} tickLine={false} axisLine={false}/><Tooltip labelFormatter={v=>new Date(v).toLocaleDateString('en-IN',{dateStyle:'medium'})} formatter={(v:number)=>[`${v}°C`,'Daily maximum']}/><ReferenceLine y={selected?.normal} stroke="#e5a21a" strokeDasharray="6 4" label={{value:'Regional reference',fill:'#9a6b0c',fontSize:11}}/><Line type="monotone" dataKey="maxTemperature" name="Maximum" stroke="#e54c1a" strokeWidth={3} dot={{r:4,fill:'#fff',strokeWidth:2}}/></LineChart></ResponsiveContainer></div><p className="model-note">{forecast?.[0]?.model??'Loading provider'} · deterministic provider forecast · DL uncertainty not yet enabled</p></section><HeatMap regions={snapshot.regions} selected={region} onSelect={setRegion}/></div>
    <div className="dashboard-grid lower"><StationFeed stations={snapshot.stations.slice(0,7)}/><AlertRail alerts={snapshot.alertList.slice(0,5)}/></div>
  </>}</>;
}

function Metric({icon,label,value,note,tone='default'}:{icon:React.ReactNode;label:string;value:string;note:string;tone?:string}){return <div className={`metric ${tone}`}><span className="metric-icon">{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></div>}
function PanelTitle({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <div className="panel-title"><div><h2>{title}</h2><p>{copy}</p></div>{action}</div>}
function HeatMap({regions:items,selected,onSelect}:{regions:Summary[];selected:Region;onSelect:(r:Region)=>void}){return <section className="panel heat-map"><PanelTitle title="Current heat risk" copy="Regional observations · select to inspect"/><div className="region-map">{items.map((item,index)=><button key={item.region} className={`region-node node-${index} ${selected===item.region?'selected':''}`} onClick={()=>onSelect(item.region)} style={{'--risk':severityColors[item.severity]} as React.CSSProperties}><span>{item.latestTemp.toFixed(1)}°</span><small>{item.region.replace(' India','')}</small></button>)}<div className="map-rings"/></div><div className="map-legend">{Object.entries(severityColors).map(([label,color])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div></section>}
function StationFeed({stations}:{stations?:Station[]}){return <section className="panel table-panel"><PanelTitle title="Live reference-point feed" copy={`${stations?.length??0} recent provider signals`} action={<a href="/stations" className="text-link">View all <ArrowRight size={14}/></a>}/>{!stations?<Loading/>:<div className="table-scroll"><table><thead><tr><th>Station</th><th>Temperature</th><th>Humidity</th><th>Source</th><th>Last seen</th></tr></thead><tbody>{stations.map(station=><tr key={station.station}><td><strong>{station.station}</strong><small>{station.location}</small></td><td className="temperature">{station.latestReading.toFixed(1)}°C</td><td>{station.humidity}%</td><td>{station.provider}</td><td>{time(station.timestamp)}</td></tr>)}</tbody></table></div>}</section>}
function AlertRail({alerts}:{alerts?:Alert[]}){return <section className="panel alert-rail"><PanelTitle title="Recent alerts" copy="Operational timeline" action={<a href="/alerts" className="text-link">View all <ArrowRight size={14}/></a>}/>{!alerts?<Loading/>:alerts.length===0?<EmptyState title="No alerts" copy="Conditions are within normal range."/>:<div className="timeline">{alerts.map(alert=><article key={alert.id}><time>{time(alert.createdAt)}</time><i style={{background:severityColors[alert.severity]}}/><div><strong>{alert.title}</strong><p>{alert.message}</p></div><Badge severity={alert.severity}/></article>)}</div>}</section>}

export function Watch({revision=0}:{revision?:number}){const [region,setRegion]=useState<Region>('Northwest India');const {data:summary,error}=useLoad<Summary[]>('/api/regions/summary',revision);const {data:forecast}=useLoad<Forecast[]>(`/api/forecast/${encodeURIComponent(region)}?days=7`,revision);return <><PageHead title="Heatwave watch" copy="Compare regional maximum-temperature forecasts against configured heat references." action={<select className="select" value={region} onChange={e=>setRegion(e.target.value as Region)}>{regions.map(r=><option key={r}>{r}</option>)}</select>}/>{error?<ErrorBox message={error}/>:!summary?<Loading/>:<div className="watch-layout"><section className="panel"><PanelTitle title="Regional risk board" copy="Ranked by departure from configured reference"/><div className="risk-list">{[...summary].sort((a,b)=>b.departure-a.departure).map(item=><button key={item.region} onClick={()=>setRegion(item.region)} className={item.region===region?'selected':''}><span className="risk-bar" style={{background:severityColors[item.severity]}}/><div><strong>{item.region}</strong><small>{item.departure>0?'+':''}{item.departure.toFixed(1)}°C departure</small></div><b>{item.latestTemp.toFixed(1)}°</b><Badge severity={item.severity}/></button>)}</div></section><section className="panel"><PanelTitle title={`${region} forecast`} copy={forecast?.[0]?.model??'Loading provider'}/><div className="forecast-days">{forecast?.map(day=><article key={day.date}><time>{new Date(day.date).toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}</time><strong>{day.maxTemperature.toFixed(1)}°C</strong><Badge severity={day.severity}/></article>)}</div></section></div>}</>}

export function Stations({revision=0}:{revision?:number}){const {data,error}=useLoad<Station[]>('/api/stations',revision);const [query,setQuery]=useState('');const filtered=useMemo(()=>data?.filter(s=>`${s.station} ${s.location} ${s.region}`.toLowerCase().includes(query.toLowerCase())),[data,query]);return <><PageHead title="Live reference points" copy="Provider observations at the configured locations reserved for future AWS integration." action={<input className="select min-w-64" placeholder="Search locations" value={query} onChange={e=>setQuery(e.target.value)}/>}/>{error?<ErrorBox message={error}/>:!filtered?<Loading/>:<section className="panel table-panel full-table"><PanelTitle title="Weather observation network" copy={`${filtered.length} of ${data?.length} reference points`}/><div className="table-scroll"><table><thead><tr><th>Point</th><th>Region</th><th>Temperature</th><th>Humidity</th><th>Wind</th><th>Daily maximum</th><th>Source</th><th>Updated</th></tr></thead><tbody>{filtered.map(s=><tr key={s.station}><td><strong>{s.station}</strong><small>{s.location}</small></td><td>{s.region}</td><td className="temperature">{s.latestReading.toFixed(1)}°C</td><td><Droplets size={13}/>{s.humidity}%</td><td><Wind size={13}/>{s.windSpeed} km/h</td><td>{s.regionalForecast.toFixed(1)}°C</td><td>{s.provider}</td><td>{time(s.timestamp)}</td></tr>)}</tbody></table></div></section>}</>}

export function Alerts({revision=0}:{revision?:number}){const {data,error,reload}=useLoad<Alert[]>('/api/alerts',revision);const [busy,setBusy]=useState('');async function acknowledge(id:string){setBusy(id);await api(`/api/alerts/${id}/acknowledge`,{method:'PATCH'});setBusy('');reload()}return <><PageHead title="Alert operations" copy="Review, acknowledge and coordinate heat-risk signals before public communication."/>{error?<ErrorBox message={error}/>:!data?<Loading/>:<div className="alerts-page">{data.map(alert=><article className="alert-row" key={alert.id}><span className="alert-symbol" style={{color:severityColors[alert.severity]}}><AlertTriangle/></span><div><div className="flex flex-wrap items-center gap-3"><h2>{alert.title}</h2><Badge severity={alert.severity}/></div><p>{alert.message}</p><small>{new Date(alert.createdAt).toLocaleString('en-IN')}</small></div>{alert.status==='active'?<button className="primary-button" disabled={busy===alert.id} onClick={()=>acknowledge(alert.id)}><Check size={16}/>{busy===alert.id?'Saving…':'Acknowledge'}</button>:<span className="acknowledged"><ShieldCheck size={16}/>Acknowledged</span>}</article>)}</div>}</>}

const stakeholders=['citizens','farmers','health agencies','local authorities'] as const;
export function Advisories(){const[region,setRegion]=useState<Region>('Northwest India');const[stakeholder,setStakeholder]=useState('citizens');const[severity,setSeverity]=useState<Severity>('Heatwave');const[text,setText]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);async function generate(){setLoading(true);setError('');try{const r=await api<{advisory:string}>('/api/advisory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region,severity,stakeholder})});setText(r.advisory)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}return <><PageHead title="Advisory studio" copy="Turn verified operational context into clear, audience-specific safety guidance."/><div className="studio-grid"><section className="panel form-panel"><label>Region</label><select className="select" value={region} onChange={e=>setRegion(e.target.value as Region)}>{regions.map(r=><option key={r}>{r}</option>)}</select><label>Severity</label><select className="select" value={severity} onChange={e=>setSeverity(e.target.value as Severity)}>{Object.keys(severityColors).map(s=><option key={s}>{s}</option>)}</select><label>Audience</label><div className="audience-grid">{stakeholders.map(s=><button key={s} onClick={()=>setStakeholder(s)} className={stakeholder===s?'selected':''}>{s}</button>)}</div><button className="primary-button justify-center" onClick={generate} disabled={loading}><Sparkles size={16}/>{loading?'Preparing guidance…':'Generate advisory'}</button></section><section className="panel advisory-output"><PanelTitle title="Prepared guidance" copy={`For ${stakeholder} · ${region}`}/>{error?<ErrorBox message={error}/>:text?<blockquote>{text}</blockquote>:<EmptyState title="Ready when you are" copy="Choose an audience and generate reviewed, contextual guidance."/>}</section></div></>}

export function System(){const {data:health,error}=useLoad<{status:string;version:string;forecastProvider:string}>('/api/health');const {data:snapshot}=useLoad<Snapshot>('/api/operations/snapshot');return <><PageHead title="System readiness" copy="Integration contracts and service health for the operational platform."/>{error?<ErrorBox message={error}/>:<div className="system-grid"><SystemCard icon={<Server/>} title="API service" status={health?.status??'Checking'} copy={health?`Version ${health.version}`:'Waiting for health check'}/><SystemCard icon={<RadioTower/>} title="Live stream" status={snapshot?.connection??'Checking'} copy="Server-sent events with heartbeat"/><SystemCard icon={<Database/>} title="Reporting sources" status={snapshot?`${snapshot.reportingStations} / ${snapshot.totalStations}`:'Checking'} copy={snapshot?`${snapshot.dataQuality}% passing quality checks`:'Waiting for provider data'}/><SystemCard icon={<Gauge/>} title="Forecast provider" status={health?.forecastProvider??'Checking'} copy="Pluggable contract ready for TCN/TFT"/></div>}<section className="panel mt-5"><PanelTitle title="DL integration boundary" copy="The forecasting contract is isolated from HTTP and persistence concerns."/><div className="architecture-flow"><span>IMD / AWS ingestion</span><ArrowRight/><span>Quality validation</span><ArrowRight/><span>Feature pipeline</span><ArrowRight/><span>Model provider</span><ArrowRight/><span>Forecast API</span></div></section></>}
function SystemCard({icon,title,status,copy}:{icon:React.ReactNode;title:string;status:string;copy:string}){return <div className="panel system-card"><span>{icon}</span><div><p>{title}</p><strong>{status}</strong><small>{copy}</small></div></div>}
